Repository GHOST-Science-Club/tree-classification-irim, pull requests merged in 2025-01, with the labels that each got.

#19 [DOCU] Expand README.md to include project description
  LICENSE
  README.md
Labels: documentation, good first issue

#22 /Add-github-workflow-pep8-lint
  .github/workflows/pep8-lint.yml
Labels: enhancement

#27 DOKU-Add-how-to-run-section
  README.md
Labels: documentation

#33 fix(model): Added 'freeze' parameter to pipeline, config and model
  src/config.yaml
  src/main.py
  src/model.py
Labels: enhancement

#29 build(workflows): Add pipeline building python env and running main
  .github/workflows/pep8-lint.yml
  .github/workflows/train-model.yml
  README.md
  requirements.txt
  src/callbacks.py
  src/config.yaml
  src/dataset.py
  src/dataset_functions.py
  src/git_functions.py
  src/main.py
  src/model.py
  src/transforms.py
  src/visualization_functions.py
Labels: enhancement
